gitRepoUrl = "https://github.com/RobloxianDemo/Roblox-Modules"
gitSourceBranch = "main"

[[classOrder]]
classes = ["Cleanser", "Player", "Signal", "ProfileService"]

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "Collection of classes and utilities for Roblox-related project development."
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[[navbar.items]]
href = "https://discord.gg/zCQTzAr"
label = "Discord"
position = "right"

[[home.features]]
title = "Very Versatile"
description = "Consisting of many extensive modules which are constantly updated!"
position = "left"

[[home.features]]
title = "Very Compact"
description = "Fit into one place that you could utilize within your project!"
position = "center"

[[home.features]]
title = "Very Simplified"
description = "Very easy to get accustomed to! Why not begin now?"
position = "right"

[footer]
style = "dark"
copyright = "Copyright © 2022 Demo. Built with Moonwave and Docusaurus."