[package]
name = "robloxiandemo/profileservice-demo"
description = "A fork of Loleris' ProfileService (MadStudioRoblox/ProfileService), which has built-in compatiblity for usage with Wally."
version = "0.1.4"
license = "MIT"

authors = [
	"loleris (https://github.com/LM-loleris)",
	"Demo (https://github.com/RobloxianDemo)"
]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"