[package]
name = "robloxiandemo/player"
description = "A custom player wrapper, which has built-in compatibility for usage with Wally."
version = "0.1.6"
license = "MIT"
authors = ["Demo (https://github.com/RobloxianDemo)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Cleanser = "robloxiandemo/cleanser@0.1.8"