[package]
name = "robloxiandemo/signal"
description = "A custom signal implementation, which has built-in compatiblity for usage with Wally."
version = "0.1.8"
license = "MIT"
authors = ["Demo (https://github.com/RobloxianDemo)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Cleanser = "robloxiandemo/cleanser@0.1.8"